- hosts: all
  become: yes
  # Don't gather facts as the setup module fails on archlinux/c101pa
  gather_facts: false

  tasks:

    - name: Delete default user
      user:
        name: alarm
        state: absent


    - name: set hostname
      hostname:
        name: "{{ hostname }}"


    - name: set timezone
      timezone:
        name: "{{ timezone }}"


    - name: full system upgrade
      when: no_upgrade is undefined
      pacman:
        update_cache: yes
        upgrade: yes


    - name: install packages
      with_items: "{{ packages }}"
      pacman:
        name: "{{ item }}"
        state: present


    - name: copy skel files
      copy:
        src: "files/skel/"
        dest: "/etc/skel/"
        owner: root
        group: root
        mode: 0755


    - name: setup sudoers
      copy:
        src: "files/sudoers"
        dest: "/etc/sudoers"
        owner: root
        group: root
        mode: 0440


    - name: reconfigure ntp
      copy:
        src: "files/ntp.conf"
        dest: "/etc/ntp.conf"
        owner: root
        group: root
        mode: 0644


    - name: configure backlight rules
      copy:
        src: "files/backlight.rules"
        dest: "/etc/udev/rules.d/backlight.rules"
        owner: root
        group: root
        mode: 0444


    - name: configure locale
      command: localectl set-x11-keymap gb chromebook


    - name: create users(s)
      with_dict: "{{ users }}"
      user:
        name: "{{ item.key }}"
        password: "{{ item.value.password }}"
        groups:
          - audio
          - docker
          - video
          - wheel
