- hosts: all
  become: yes
  # Don't gather facts as the setup module fails on archlinux/c101pa
  gather_facts: false

  tasks:

    - name: Delete default user
      user:
        name: alarm
        state: absent


    - name: set hostname
      hostname:
        name: "{{ hostname }}"


    - name: set timezone
      timezone:
        name: "{{ timezone }}"


    - name: full system upgrade
      pacman:
        update_cache: yes
        upgrade: yes


    - name: install packages
      with_items: "{{ packages }}"
      pacman:
        name: "{{ item }}"
        state: present


    - name: copy system files
      with_dict: "{{ system_files }}"
      copy:
        src: "files/{{ item.key }}"
        dest: "{{ item.value.dest }}"
        owner: "{{ item.value.owner }}"
        group: "{{ item.value.group }}"
        mode: "{{ item.value.mode }}"


    - name: create users(s)
      with_dict: "{{ users }}"
      user:
        name: "{{ item.key }}"
        password: "{{ item.value.password }}"
        groups:
          - audio
          - docker
          - video
          - wheel
