#!/bin/bash
brightness=/sys/class/backlight/backlight/brightness

min=2000
max=62000
step=4000

setBrightness() {
   cur=$(cat $brightness)
   round=$(($cur/$step*$step+$min))
   new=$((round+$1))
   if [[ $new -ge $min && $new -le $max ]]; then
      echo $new > $brightness
   fi
}

usage() {
  echo "usage: backlight <incr|decr>"
}


if [[ ! $# -eq 1 ]]; then
  usage
  exit 0
fi

case "$1" in
   "incr")
      setBrightness $step
      ;;
   "decr")
      setBrightness -$step
      ;;
   *)
      usage
      ;;
esac

